apiVersion: v1
kind: Service
metadata:
  name: echoheaders-loc
  labels:
    app: echoheaders-loc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders-loc
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders-loc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders-loc
    spec:
      containers:
      - name: echoheaders-loc
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080